WIP: feat: karma system
rickklaasboer/wego-overseer pull request #65
Opened 2022-12-11 16:27 UTC by rickklaasboer

2022-12-14 18:07 UTC, Kabelbaan requested changes

2022-12-14 18:07 UTC, Kabelbaan commented on src/commands/karma/KarmaUserResetCommand.ts
> +        if (submitted) {
reduce nesting?

2022-12-14 18:08 UTC, Jessuhh requested changes

2022-12-14 18:08 UTC, Jessuhh commented on src/commands/karma/KarmaUserResetCommand.ts
> +        const isAdmin = interaction.memberPermissions?.has(
Maybe also only allow admins to enable and disable karma channels? ;)

2022-12-14 18:08 UTC, Jessuhh commented on src/lang/en.json
> +    "karka.channel.reset.not_a_karma_channel": "Whoops, looks like `#%s` is not a karma channel."
`karka` => `karma`

2022-12-15 09:54 UTC, NiekKleverkamp requested changes
Ephemeral errors pl0x

2022-12-15 09:54 UTC, NiekKleverkamp commented on src/commands/karma/KarmaChannelDisableCommand.ts
> +                t('errors.common.command.no_permission', interaction.user.id),
Make ephemeral?

2022-12-15 09:54 UTC, NiekKleverkamp commented on src/commands/karma/KarmaChannelEnableCommand.ts
> +                t('errors.common.command.no_permission', interaction.user.id),
Make ephemeral?

2022-12-15 09:54 UTC, NiekKleverkamp commented on src/commands/karma/KarmaUserResetCommand.ts
> +                t('errors.common.command.no_permission', interaction.user.id),
Make ephemeral?

2022-12-15 09:54 UTC, NiekKleverkamp commented on src/commands/karma/KarmaUserResetCommand.ts
> +            await submitted.reply('Usernames did not match, please try again.');
Make ephemeral?

2022-12-15 09:54 UTC, NiekKleverkamp commented on src/commands/karma/KarmaUserResetCommand.ts
> +        await submitted.reply(
Could be made ephemeral I suppose :P

2022-12-16 15:46 UTC, NiekKleverkamp approved these changes
lgtm

2022-12-16 16:10 UTC, Jessuhh approved these changes
LGTM! Is there a reason why the enable and disable karma channel command are separated? Could you not make one command do both?

2022-12-16 16:15 UTC, merged